
services:
  broker-service:
    build:
      context: .
      dockerfile: ./broker-service.dockerfile
    ports:
      - 8080:80
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  logger-service:
    build:
      context: .
      dockerfile: ./logger-service.dockerfile
    ports:
      - 8100:80
    restart: always
    deploy:
      mode: replicated
      replicas: 1
  
  auth-service:
    build:
      context: .
      dockerfile: ./auth-service.dockerfile
    ports:
      - 8090:80
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=auth_user dbname=users password=manager sslmode=disable"
  
  front-end:
    build:
      context: .
      dockerfile: ./front-end.dockerfile
    ports:
      - 80:80
    restart: always
    deploy:
      mode: replicated
      replicas: 1
  
  postgres:
    image: postgres:14.2
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=users
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=manager
    command: [ "postgres", "-c", "log_statement=all" ]
    ports:
      - 5432:5432

  mongo:
    image: mongo:4.2.16-bionic
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=logger
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo:/data/db